version: "3.4"

services:

  vocaloid:
    build:
      dockerfile: ./docker/vocaloid.dockerfile
      context: ./
    environment:
      DISPLAY: host.docker.internal:0
    environment:
      - SSH_AUTH_SOCK=/usr/bin/ssh-agent
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./vocaloid
        target: /vocaloid
      - ${SSH_AUTH_SOCK}:/ssh-agent
      # for xwindows
      #- type: bind
      #  source: /tmp/.X11-unix
      #  target: /tmp/.X11-unix